"""initial schema

Revision ID: 9eeaf21b5a11
Revises:
Create Date: 2026-07-31 08:37:27.615885

This migration reconstructs the schema that existed when Alembic was
introduced.

The original generated migration was empty because the application
tables already existed in the development database. A fresh database
therefore received only alembic_version and failed at the next
migration.

This schema deliberately represents the historical state before
fbd6e3c0c923:

* inventory_source uses source_type
* inventory_source.credential_id has no FK or index yet
* Project has no inventory_id
* ProjectStep uses inventory_source_id
* later inventory and Package snapshot tables do not exist yet
"""

from alembic import op
import sqlalchemy as sa


revision = "9eeaf21b5a11"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "credential",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "owner",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "security_scope",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "credential_type",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "encrypted_data",
            sa.LargeBinary(),
            nullable=True,
        ),
        sa.Column(
            "secret_format_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner",
            "name",
            name="uq_credential_owner_name",
        ),
    )

    op.create_index(
        "ix_credential_owner",
        "credential",
        ["owner"],
        unique=False,
    )

    op.create_index(
        "ix_credential_security_scope",
        "credential",
        ["security_scope"],
        unique=False,
    )

    op.create_index(
        "ix_credential_credential_type",
        "credential",
        ["credential_type"],
        unique=False,
    )

    op.create_table(
        "repository",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "url",
            sa.String(length=1000),
            nullable=False,
        ),
        sa.Column(
            "default_branch",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "credential_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "last_sync_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_sync_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "last_commit",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "last_commit_message",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "last_commit_author",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "last_commit_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "inventory_source",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "endpoint",
            sa.String(length=1000),
            nullable=False,
        ),
        sa.Column(
            "credential_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "verify_tls",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "config_json",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "last_sync_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "project",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "owner",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "security_scope",
            sa.String(length=20),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "project_step",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "repository_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "inventory_source_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "playbook",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "limit",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "skip_tags",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "verbosity",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "continue_on_failure",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inventory_source_id"],
            ["inventory_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "position",
            name="uq_project_step_position",
        ),
    )

    op.create_index(
        "ix_project_step_project_id",
        "project_step",
        ["project_id"],
        unique=False,
    )

    op.create_table(
        "project_step_credential",
        sa.Column(
            "project_step_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "credential_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_step_id"],
            ["project_step.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_step_id",
            "credential_id",
        ),
    )

    op.create_table(
        "job",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "project_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "requested_by",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "exit_code",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "message",
            sa.Text(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_job_project_id",
        "job",
        ["project_id"],
        unique=False,
    )

    op.create_index(
        "ix_job_status",
        "job",
        ["status"],
        unique=False,
    )

    op.create_table(
        "job_repository_snapshot",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "repository_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "repository_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "repository_url",
            sa.String(length=1000),
            nullable=False,
        ),
        sa.Column(
            "repository_commit",
            sa.String(length=64),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id",
            "repository_id",
            name="uq_job_repository_snapshot",
        ),
    )

    op.create_index(
        "ix_job_repository_snapshot_job_id",
        "job_repository_snapshot",
        ["job_id"],
        unique=False,
    )

    op.create_table(
        "job_credential_snapshot",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "credential_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "credential_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "credential_owner",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "credential_type",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "encrypted_data",
            sa.LargeBinary(),
            nullable=False,
        ),
        sa.Column(
            "secret_format_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_job_credential_snapshot_job_id",
        "job_credential_snapshot",
        ["job_id"],
        unique=False,
    )

    op.create_index(
        "ix_job_credential_snapshot_credential_id",
        "job_credential_snapshot",
        ["credential_id"],
        unique=False,
    )

    op.create_index(
        "ix_job_credential_snapshot_credential_owner",
        "job_credential_snapshot",
        ["credential_owner"],
        unique=False,
    )

    op.create_index(
        "ix_job_credential_snapshot_credential_type",
        "job_credential_snapshot",
        ["credential_type"],
        unique=False,
    )

    op.create_table(
        "job_step",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "project_step_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "job_repository_snapshot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "playbook",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "limit",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "skip_tags",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "verbosity",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "continue_on_failure",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "exit_code",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "command",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "stdout",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "stderr",
            sa.Text(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_repository_snapshot_id"],
            ["job_repository_snapshot.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id",
            "position",
            name="uq_job_step_position",
        ),
    )

    op.create_index(
        "ix_job_step_job_id",
        "job_step",
        ["job_id"],
        unique=False,
    )

    op.create_index(
        "ix_job_step_job_repository_snapshot_id",
        "job_step",
        ["job_repository_snapshot_id"],
        unique=False,
    )

    op.create_table(
        "job_step_credential_snapshot",
        sa.Column(
            "job_step_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "job_credential_snapshot_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_credential_snapshot_id"],
            ["job_credential_snapshot.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_step_id"],
            ["job_step.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "job_step_id",
            "job_credential_snapshot_id",
        ),
    )


def downgrade():
    op.drop_table(
        "job_step_credential_snapshot"
    )

    op.drop_index(
        "ix_job_step_job_repository_snapshot_id",
        table_name="job_step",
    )

    op.drop_index(
        "ix_job_step_job_id",
        table_name="job_step",
    )

    op.drop_table(
        "job_step"
    )

    op.drop_index(
        "ix_job_credential_snapshot_credential_type",
        table_name="job_credential_snapshot",
    )

    op.drop_index(
        "ix_job_credential_snapshot_credential_owner",
        table_name="job_credential_snapshot",
    )

    op.drop_index(
        "ix_job_credential_snapshot_credential_id",
        table_name="job_credential_snapshot",
    )

    op.drop_index(
        "ix_job_credential_snapshot_job_id",
        table_name="job_credential_snapshot",
    )

    op.drop_table(
        "job_credential_snapshot"
    )

    op.drop_index(
        "ix_job_repository_snapshot_job_id",
        table_name="job_repository_snapshot",
    )

    op.drop_table(
        "job_repository_snapshot"
    )

    op.drop_index(
        "ix_job_status",
        table_name="job",
    )

    op.drop_index(
        "ix_job_project_id",
        table_name="job",
    )

    op.drop_table(
        "job"
    )

    op.drop_table(
        "project_step_credential"
    )

    op.drop_index(
        "ix_project_step_project_id",
        table_name="project_step",
    )

    op.drop_table(
        "project_step"
    )

    op.drop_table(
        "project"
    )

    op.drop_table(
        "inventory_source"
    )

    op.drop_table(
        "repository"
    )

    op.drop_index(
        "ix_credential_credential_type",
        table_name="credential",
    )

    op.drop_index(
        "ix_credential_security_scope",
        table_name="credential",
    )

    op.drop_index(
        "ix_credential_owner",
        table_name="credential",
    )

    op.drop_table(
        "credential"
    )
